// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0rHSbN8i2wkYdSvCAgda9_hFLL37la-I',
    appId: '1:752489971803:web:954966b8067f38968dff7e',
    messagingSenderId: '752489971803',
    projectId: 'sketch-paste',
    authDomain: 'sketch-paste.firebaseapp.com',
    storageBucket: 'sketch-paste.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0en5EMEZcCMTcEfYtqQfS5Dt2j83xw0c',
    appId: '1:752489971803:android:726e8f18e4b842cc8dff7e',
    messagingSenderId: '752489971803',
    projectId: 'sketch-paste',
    storageBucket: 'sketch-paste.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYexlEaZ1TSIkZilJWBRdkXTc7M8VRZsk',
    appId: '1:752489971803:ios:62df603cac1d6fd48dff7e',
    messagingSenderId: '752489971803',
    projectId: 'sketch-paste',
    storageBucket: 'sketch-paste.appspot.com',
    iosClientId:
        '752489971803-sd92aonrkgoh6rkbfui9ir50asn86m9l.apps.googleusercontent.com',
    iosBundleId: 'app.tinyhacks.copypaste',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYexlEaZ1TSIkZilJWBRdkXTc7M8VRZsk',
    appId: '1:752489971803:ios:62df603cac1d6fd48dff7e',
    messagingSenderId: '752489971803',
    projectId: 'sketch-paste',
    storageBucket: 'sketch-paste.appspot.com',
    iosClientId:
        '752489971803-sd92aonrkgoh6rkbfui9ir50asn86m9l.apps.googleusercontent.com',
    iosBundleId: 'app.tinyhacks.copypaste',
  );
}
