/// Flutter icons MenubarIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MenubarIcons
///      fonts:
///       - asset: fonts/MenubarIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class MenubarIcons {
  MenubarIcons._();

  static const _kFontFam = 'MenubarIcons';
  static const String? _kFontPkg = null;

  static const IconData eraser =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pen =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
