name: Flutter Run Tests

env:
  flutter_version: '3.0.x'

on: 
  push
jobs:
  Running-Tests:
    name: Running Tests on 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            flutter_path: /opt/hostedtoolcache/flutter
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Manage Flutter Caching
        id: cache-flutter
        uses: actions/cache@v3
        with: 
          path: ${{ matrix.flutter_path }}
          key: ${{ runner.os }}-flutter-install-cache-${{ env.flutter_version }}
      - name: Set up flutter
        uses: subosito/flutter-action@v2.4.0
        with:
          channel: 'stable'
          flutter-version: ${{ env.flutter_version }}
      - name: Preparing Flutter Packages
        run: flutter pub get
      - name: Testing
        run: flutter test